"""Markdown formatting helpers."""

from datetime import datetime, timezone


def md_heading(title: str, level: int = 2) -> str:
    return f"{'#' * level} {title}\n\n"


def generation_header(agent_name: str) -> str:
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    return (
        "<!-- Generated by BridgeMind AI -->\n"
        f"**Agent:** {agent_name}  \n"
        f"**Generated:** {timestamp}\n\n"
        "---\n\n"
    )
